### ISSUE TITLE
로컬스토리지을 사용할 예정이니?

### ISSUE THREAD

**Issue by mixed** [KimDahye/pomodoro#1]
보니깐 값을 저장하고 그런 기능이 있던데?

**Comment by KimDahye** [comment]
원래는 (DB 서버를 운영하고 싶지 않아서..) indexed DB나, sqlLite?등으로 로컬 메모리를 사용해서 데이터를 저장하려고 했는데요. 사람들의 리뷰를 죽 살펴보니, 기기마다 동기화를 해놓고 싶다는 의견들이 많아서, 일단 먼저 온라인에서 잘 돌아가도록 한 뒤, 오프라인으로도 돌아가도록 나중에 적용해볼까 생각중이에요
